import { User, Task, AppNotification, ProjectDetails } from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'user_leader',
    name: 'Alex Morgan',
    email: 'alex.morgan@hackteam.io',
    role: 'leader',
    teamRole: 'Team Leader & Lead Architect',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    githubUsername: 'alexm-lead',
    skills: ['System Architecture', 'TypeScript', 'Cloud Infrastructure', 'Product Strategy'],
    bio: 'Team Leader and Fullstack Architect driving system architecture, sprint delivery, and quality assurance.',
  },
  {
    id: 'user_sarah',
    name: 'Sarah Chen',
    email: 'sarah.chen@hackteam.io',
    role: 'member',
    teamRole: 'Frontend & UI Lead',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80',
    githubUsername: 'sarahc-dev',
    skills: ['React 19', 'Tailwind CSS', 'Framer Motion', 'Accessible UI'],
    bio: 'Crafting responsive user interfaces, dashboard micro-interactions, and component systems.',
  },
  {
    id: 'user_marcus',
    name: 'Marcus Vance',
    email: 'marcus.vance@hackteam.io',
    role: 'member',
    teamRole: 'Backend & Data Lead',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    githubUsername: 'marcusv-api',
    skills: ['Node.js', 'PostgreSQL', 'Redis', 'API Gateway'],
    bio: 'Designing high-throughput API endpoints, database schemas, and microservice communications.',
  },
  {
    id: 'user_priya',
    name: 'Priya Sharma',
    email: 'priya.sharma@hackteam.io',
    role: 'member',
    teamRole: 'AI & ML Engineer',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    githubUsername: 'priya-ai',
    skills: ['Gemini 2.5 API', 'PyTorch', 'Vector Embeddings', 'RAG Pipelines'],
    bio: 'Building intelligent inference pipelines, agentic orchestration, and multimodal prompt systems.',
  },
  {
    id: 'user_david',
    name: 'David Kim',
    email: 'david.kim@hackteam.io',
    role: 'member',
    teamRole: 'DevOps & Fullstack',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    githubUsername: 'davidk-cloud',
    skills: ['Docker', 'CI/CD Pipelines', 'Cloud Run', 'Monitoring'],
    bio: 'Managing automated deployments, containerization, observability metrics, and build pipelines.',
  },
  {
    id: 'user_elena',
    name: 'Elena Rostova',
    email: 'elena.rostova@hackteam.io',
    role: 'member',
    teamRole: 'Product Designer & QA',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80',
    githubUsername: 'elena-ux',
    skills: ['Figma Prototyping', 'User Testing', 'Cypress E2E', 'Design Tokens'],
    bio: 'Translating user requirements into design systems, validating edge cases, and running QA suites.',
  },
];

export const INITIAL_PROJECT: ProjectDetails = {
  name: 'OmniSprint - Collaborative Hackathon Platform',
  tagline: 'High-velocity collaborative sprint orchestration and real-time deliverable tracking platform.',
  hackathonName: 'Global Open Innovation Hackathon 2026',
  deadlineTimestamp: new Date(Date.now() + 18 * 3600 * 1000 + 42 * 60 * 1000).toISOString(), // ~18.5 hours from now
  githubRepoUrl: 'https://github.com/hackteam-alpha/omnisprint-core',
  demoUrl: 'https://omnisprint-demo.cloudrun.app',
  docsUrl: 'https://docs.omnisprint.dev/architecture',
  figmaUrl: 'https://figma.com/file/omnisprint-prototype-2026',
  description: 'A collaborative hackathon sprint and engineering workflow platform enabling rapid feature development, automated CI/CD pipeline builds, AI-assisted code reviews, and real-time team deliverable evaluations.',
  techStack: ['React 19', 'TypeScript', 'Tailwind CSS', 'Node.js Express', 'PostgreSQL', 'Docker', 'Redis'],
};

export const INITIAL_TASKS: Task[] = [
  // Sarah Chen's tasks
  {
    id: 'task-101',
    title: 'Implement Interactive Sprint Burndown & Metrics Visualizer',
    description: 'Build the interactive sprint velocity component with real-time waveform throughput graphs, milestone progress bars, and critical deadline alert badges.',
    assignedToId: 'user_sarah',
    assignedById: 'user_leader',
    assignedDate: '2026-09-07T09:00:00.000Z',
    deadline: '2026-09-08T18:00:00.000Z',
    priority: 'high',
    status: 'completed',
    githubBranch: 'feature/metrics-visualizer',
    githubIssueNumber: 12,
    tags: ['Frontend', 'Charts', 'UI Component'],
    submission: {
      id: 'sub-101',
      taskId: 'task-101',
      memberId: 'user_sarah',
      submittedAt: '2026-09-08T02:15:00.000Z',
      notes: 'Implemented the canvas sprint metrics graph with dynamic velocity simulation and customizable milestone threshold styling.',
      githubUrl: 'https://github.com/hackteam-alpha/omnisprint-core/pull/14',
      projectUrl: 'https://omnisprint-demo.cloudrun.app/metrics',
      attachmentName: 'metrics-ui-preview.mp4',
    },
    review: {
      id: 'rev-101',
      taskId: 'task-101',
      reviewerId: 'user_leader',
      reviewedAt: '2026-09-08T04:30:00.000Z',
      score: 95,
      feedback: 'Outstanding visual design and fluid rendering. High responsiveness on mobile and accessible ARIA live regions.',
      verdict: 'approved',
    },
  },
  {
    id: 'task-102',
    title: 'Dark/Light Theme System & Accessibility Pass',
    description: 'Ensure all dashboard components adhere to WCAG AA color contrast standards and implement dark mode toggle state.',
    assignedToId: 'user_sarah',
    assignedById: 'user_leader',
    assignedDate: '2026-09-08T06:00:00.000Z',
    deadline: '2026-09-09T02:00:00.000Z',
    priority: 'medium',
    status: 'submitted', // Ready for leader to review!
    githubBranch: 'feature/theme-a11y',
    githubIssueNumber: 19,
    tags: ['Frontend', 'A11y', 'Tailwind'],
    submission: {
      id: 'sub-102',
      taskId: 'task-102',
      memberId: 'user_sarah',
      submittedAt: '2026-09-08T11:20:00.000Z',
      notes: 'Updated color tokens for 4.5:1 ratio across all text elements. Added keyboard navigation tab indices for modals.',
      githubUrl: 'https://github.com/hackteam-alpha/omnisprint-core/pull/22',
      projectUrl: 'https://omnisprint-demo.cloudrun.app/settings',
      attachmentName: 'lighthouse-accessibility-audit-98.pdf',
    },
  },
  {
    id: 'task-103',
    title: 'Mobile Navigation Drawer & Gesture Handling',
    description: 'Implement responsive mobile navigation drawer with touch gesture dismiss and quick emergency switch.',
    assignedToId: 'user_sarah',
    assignedById: 'user_leader',
    assignedDate: '2026-09-08T10:00:00.000Z',
    deadline: '2026-09-09T14:00:00.000Z',
    priority: 'low',
    status: 'in_progress',
    githubBranch: 'feature/mobile-drawer',
    githubIssueNumber: 26,
    tags: ['Frontend', 'Mobile', 'Navigation'],
  },

  // Marcus Vance's tasks
  {
    id: 'task-201',
    title: 'Design Scalable PostgreSQL Core Registry & Schema Migration',
    description: 'Create normalized relational schema for sprint deliverables, evaluation scores, audit logs, and team event queues.',
    assignedToId: 'user_marcus',
    assignedById: 'user_leader',
    assignedDate: '2026-09-07T08:30:00.000Z',
    deadline: '2026-09-08T14:00:00.000Z',
    priority: 'urgent',
    status: 'completed',
    githubBranch: 'backend/db-schema-v1',
    githubIssueNumber: 3,
    tags: ['Backend', 'PostgreSQL', 'Database'],
    submission: {
      id: 'sub-201',
      taskId: 'task-201',
      memberId: 'user_marcus',
      submittedAt: '2026-09-07T22:45:00.000Z',
      notes: 'Created full DDL scripts, indexes on user_id and task_priority, and seed scripts with synthetic team records.',
      githubUrl: 'https://github.com/hackteam-alpha/omnisprint-core/pull/8',
      projectUrl: 'https://github.com/hackteam-alpha/omnisprint-core/blob/main/docs/schema.md',
      attachmentName: 'schema-erd-diagram.png',
    },
    review: {
      id: 'rev-201',
      taskId: 'task-201',
      reviewerId: 'user_leader',
      reviewedAt: '2026-09-08T01:10:00.000Z',
      score: 92,
      feedback: 'Great indexing strategy for query performance. Clean foreign keys and audit timestamp triggers.',
      verdict: 'approved',
    },
  },
  {
    id: 'task-202',
    title: 'Implement Webhook Ingestion for CI/CD & Git Events',
    description: 'Build secure HMAC-authenticated endpoint to receive repository push, pull request, and deployment alerts in real-time.',
    assignedToId: 'user_marcus',
    assignedById: 'user_leader',
    assignedDate: '2026-09-08T07:15:00.000Z',
    deadline: '2026-09-09T01:00:00.000Z',
    priority: 'high',
    status: 'submitted', // Ready for leader review!
    githubBranch: 'backend/git-webhook',
    githubIssueNumber: 15,
    tags: ['Backend', 'Webhooks', 'Security'],
    submission: {
      id: 'sub-202',
      taskId: 'task-202',
      memberId: 'user_marcus',
      submittedAt: '2026-09-08T10:45:00.000Z',
      notes: 'Added POST /api/v1/git/webhook with cryptographic signature verification, rate limiting, and automated queue fallback.',
      githubUrl: 'https://github.com/hackteam-alpha/omnisprint-core/pull/18',
      projectUrl: 'https://omnisprint-api.cloudrun.app/health',
      attachmentName: 'postman-collection-webhook.json',
    },
  },
  {
    id: 'task-203',
    title: 'Redis Pub/Sub Layer for Real-Time Sprint Event Broadcasts',
    description: 'Configure real-time state synchronization across team dashboards using Redis streams and WebSockets.',
    assignedToId: 'user_marcus',
    assignedById: 'user_leader',
    assignedDate: '2026-09-08T11:00:00.000Z',
    deadline: '2026-09-09T09:00:00.000Z',
    priority: 'medium',
    status: 'pending',
    githubBranch: 'backend/redis-pubsub',
    githubIssueNumber: 27,
    tags: ['Backend', 'Redis', 'Realtime'],
  },

  // Priya Sharma's tasks
  {
    id: 'task-301',
    title: 'Fine-tune AI Code Review & Sprint Summarization Prompts',
    description: 'Engineer structured schema output for deliverable quality assessment, code complexity scoring, and automated release note generation.',
    assignedToId: 'user_priya',
    assignedById: 'user_leader',
    assignedDate: '2026-09-07T10:00:00.000Z',
    deadline: '2026-09-08T12:00:00.000Z',
    priority: 'urgent',
    status: 'completed',
    githubBranch: 'ai/code-review-prompts',
    githubIssueNumber: 5,
    tags: ['AI/ML', 'Gemini API', 'Prompt Design'],
    submission: {
      id: 'sub-301',
      taskId: 'task-301',
      memberId: 'user_priya',
      submittedAt: '2026-09-08T03:30:00.000Z',
      notes: 'Achieved high accuracy across 80 benchmark pull request scenarios using structured JSON schema output and few-shot evaluation guidelines.',
      githubUrl: 'https://github.com/hackteam-alpha/omnisprint-core/pull/12',
      projectUrl: 'https://omnisprint-demo.cloudrun.app/ai-summarizer',
      attachmentName: 'accuracy-benchmark-matrix.csv',
    },
    review: {
      id: 'rev-301',
      taskId: 'task-301',
      reviewerId: 'user_leader',
      reviewedAt: '2026-09-08T05:00:00.000Z',
      score: 98,
      feedback: 'Incredible work! The structured outputs guarantee reliable summaries and clear actionable recommendations.',
      verdict: 'approved',
    },
  },
  {
    id: 'task-302',
    title: 'Multimodal Audio Transcription for Sprint Standup Voice Notes',
    description: 'Integrate speech-to-text with technical vocabulary filtering for instant daily standup summaries.',
    assignedToId: 'user_priya',
    assignedById: 'user_leader',
    assignedDate: '2026-09-08T08:00:00.000Z',
    deadline: '2026-09-09T03:00:00.000Z',
    priority: 'high',
    status: 'in_progress',
    githubBranch: 'ai/standup-notes',
    githubIssueNumber: 21,
    tags: ['AI/ML', 'Speech', 'NLP'],
  },

  // David Kim's tasks
  {
    id: 'task-401',
    title: 'Configure Multi-stage Dockerfile and Cloud Run CI/CD Pipeline',
    description: 'Set up GitHub Actions to automatically run tests, build optimized multi-stage container images, and deploy to Cloud Run.',
    assignedToId: 'user_david',
    assignedById: 'user_leader',
    assignedDate: '2026-09-07T09:30:00.000Z',
    deadline: '2026-09-08T15:00:00.000Z',
    priority: 'urgent',
    status: 'completed',
    githubBranch: 'devops/docker-cloudrun-deploy',
    githubIssueNumber: 2,
    tags: ['DevOps', 'Docker', 'CI/CD'],
    submission: {
      id: 'sub-401',
      taskId: 'task-401',
      memberId: 'user_david',
      submittedAt: '2026-09-07T21:00:00.000Z',
      notes: 'Container image size trimmed to 84MB via alpine node runtime. Deployment pipeline runs in under 90 seconds.',
      githubUrl: 'https://github.com/hackteam-alpha/omnisprint-core/pull/6',
      projectUrl: 'https://omnisprint-demo.cloudrun.app',
      attachmentName: 'build-metrics-report.json',
    },
    review: {
      id: 'rev-401',
      taskId: 'task-401',
      reviewerId: 'user_leader',
      reviewedAt: '2026-09-08T00:45:00.000Z',
      score: 94,
      feedback: 'Fast builds and rock-solid healthcheck configuration. Clean secrets management via Google Secret Manager.',
      verdict: 'approved',
    },
  },
  {
    id: 'task-402',
    title: 'Set up Prometheus Metrics and Grafana Telemetry Dashboard',
    description: 'Export response latency, P99 API response times, and task processing queue sizes to Prometheus endpoint.',
    assignedToId: 'user_david',
    assignedById: 'user_leader',
    assignedDate: '2026-09-08T09:00:00.000Z',
    deadline: '2026-09-09T04:00:00.000Z',
    priority: 'medium',
    status: 'in_progress',
    githubBranch: 'devops/prometheus-metrics',
    githubIssueNumber: 23,
    tags: ['DevOps', 'Monitoring', 'Telemetry'],
  },

  // Elena Rostova's tasks
  {
    id: 'task-501',
    title: 'Team Collaboration Hub High-Fidelity Figma Prototype',
    description: 'Design the 3-step deliverable review flow, color-coded priority cards, and evaluation modal for the final pitch presentation.',
    assignedToId: 'user_elena',
    assignedById: 'user_leader',
    assignedDate: '2026-09-07T08:00:00.000Z',
    deadline: '2026-09-08T11:00:00.000Z',
    priority: 'high',
    status: 'completed',
    githubBranch: 'design/collab-hub-v1',
    githubIssueNumber: 1,
    tags: ['Design', 'Figma', 'UX/UI'],
    submission: {
      id: 'sub-501',
      taskId: 'task-501',
      memberId: 'user_elena',
      submittedAt: '2026-09-07T20:30:00.000Z',
      notes: 'Completed complete Figma prototype with interactive clickable user states and exported SVG asset bundle.',
      githubUrl: 'https://github.com/hackteam-alpha/omnisprint-core/pull/4',
      projectUrl: 'https://figma.com/file/omnisprint-prototype-2026',
      attachmentName: 'pitch-deck-mockups.pdf',
    },
    review: {
      id: 'rev-501',
      taskId: 'task-501',
      reviewerId: 'user_leader',
      reviewedAt: '2026-09-07T23:30:00.000Z',
      score: 91,
      feedback: 'Very intuitive deliverable workflow. Visual hierarchy makes it easy for judges and team members to track progress.',
      verdict: 'approved',
    },
  },
  {
    id: 'task-502',
    title: 'Conduct End-to-End Cypress Integration & Bug Bash Test Suite',
    description: 'Write automated browser test scripts for the task assignment form, submission review flow, and status updates.',
    assignedToId: 'user_elena',
    assignedById: 'user_leader',
    assignedDate: '2026-09-08T07:45:00.000Z',
    deadline: '2026-09-08T22:00:00.000Z',
    priority: 'high',
    status: 'submitted', // Ready for review!
    githubBranch: 'qa/cypress-integration-tests',
    githubIssueNumber: 17,
    tags: ['QA', 'Testing', 'Cypress'],
    submission: {
      id: 'sub-502',
      taskId: 'task-502',
      memberId: 'user_elena',
      submittedAt: '2026-09-08T11:50:00.000Z',
      notes: 'Added 16 passing E2E scenarios covering form validation, edge cases with missing deliverables, and network retry tests.',
      githubUrl: 'https://github.com/hackteam-alpha/omnisprint-core/pull/20',
      projectUrl: 'https://omnisprint-demo.cloudrun.app/tests',
      attachmentName: 'cypress-test-run-recording.mp4',
    },
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    userId: 'user_leader',
    senderName: 'Sarah Chen',
    senderAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80',
    title: 'New Work Submitted for Review',
    message: 'Sarah Chen submitted "Dark/Light Theme System & Accessibility Pass" for your review with Pull Request #22.',
    timestamp: '25 minutes ago',
    read: false,
    type: 'task_submitted',
    taskId: 'task-102',
  },
  {
    id: 'notif-2',
    userId: 'user_leader',
    senderName: 'Elena Rostova',
    senderAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80',
    title: 'QA Test Suite Ready for Review',
    message: 'Elena Rostova submitted "Conduct End-to-End Cypress Integration & Bug Bash Test Suite".',
    timestamp: '18 minutes ago',
    read: false,
    type: 'task_submitted',
    taskId: 'task-502',
  },
  {
    id: 'notif-3',
    userId: 'user_leader',
    senderName: 'Marcus Vance',
    senderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    title: 'Webhook Integration Submitted',
    message: 'Marcus Vance submitted "Implement Webhook Ingestion for CI/CD & Git Events".',
    timestamp: '1 hour ago',
    read: false,
    type: 'task_submitted',
    taskId: 'task-202',
  },
  {
    id: 'notif-4',
    userId: 'user_sarah',
    senderName: 'Alex Morgan',
    senderAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    title: 'Task Approved & Scored (95/100)!',
    message: 'Alex Morgan reviewed your submission for "Implement Interactive Sprint Burndown & Metrics Visualizer" and gave you 95/100.',
    timestamp: '8 hours ago',
    read: true,
    type: 'score_awarded',
    taskId: 'task-101',
  },
  {
    id: 'notif-5',
    userId: 'user_priya',
    senderName: 'Alex Morgan',
    senderAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    title: 'Outstanding Score (98/100)!',
    message: 'Alex Morgan gave you a 98/100 for "Fine-tune AI Code Review & Sprint Summarization Prompts".',
    timestamp: '7 hours ago',
    read: true,
    type: 'score_awarded',
    taskId: 'task-301',
  },
];
